# Generated by Django 4.2.25 on 2025-10-15 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('meeting_place', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('length_km', models.DecimalField(decimal_places=2, help_text='Length in kilometers', max_digits=5)),
                ('max_capacity', models.PositiveIntegerField(help_text='Maximum number of participants')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False, help_text='Mark if the user attended the run')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['signed_up_at'],
                'unique_together': {('user', 'run')},
            },
        ),
    ]
